### ISSUE TITLE
Do we need the downlevelIteration flag as well to use this module?

### ISSUE THREAD

**Issue by igozali** [ryanelian/ts-polyfill#3]
Hi, first of all, thanks a lot for maintaining this package!

Just had a quick question, should we also enable the `downlevelIteration` compiler option in our `tsconfig.json` file together with using this module? I'm not completely sure, but I had some problems with [this issue](https://github.com/Microsoft/TypeScript/issues/8856) in Typescript which hasn't been fixed (regarding using spread operator on non-iterables).

**Comment by ryanelian** [comment]
Hello, thank you for bringing this issue to my attention. Very interesting!

I'll quote Arnavion on this one:

> The spread operator on Set, etc is only supported when targeting ES6, since it requires the type to implement [Symbol.iterator]() which only exists in ES6. When targeting ES5, the spread operator is only allowed for arrays (and maybe for strings and other array-likes in the future).

> So the compiler emits a call to .slice() because it expects to be emitting it for arrays. 

Hence, I'll draw my conclusion:

- If you are targeting ES5 and only wish to use ES 2015 collections (Map, Set, etc.) without iterating over it (`for-of` / `...`) you don't need to use downlevel iteration.

- However, if you absolutely need to iterate on non-Array, you probably should add that flag.

- If you wish to iterate over non-Array ***without*** using downlevel iteration flag, simply use `Array.from` method.
