### ISSUE TITLE
es2020-globalThis polyfill

### ISSUE THREAD

**Issue by ryanelian** [ryanelian/ts-polyfill#7]
Basically, there's NO TypeScript libs for `globalThis` 

https://github.com/tc39/proposal-global

However, TypeScript does NOT transpile references to `globalThis` when targeting earlier ECMAScript versions.

https://devblogs.microsoft.com/typescript/announcing-typescript-3-4/#type-checking-for-globalthis

Which means, this will be the first time a polyfill will be provided without a corresponding lib.

Why 2020? Because V8 devs said so: https://v8.dev/features/globalthis

EDIT:

https://github.com/zloirock/core-js/blob/v3.3.4/packages/core-js/modules/esnext.global-this.js

`// TODO: Remove from core-js@4`

globalThis polyfill will be removed from core-js 4 potentially. So not sure if should be included in ts-polyfill.

**Comment by zloirock** [comment]
> globalThis polyfill will be removed from core-js 4 potentially. So not sure if should be included in ts-polyfill.

[It should be removed from proposals since it's moved to stable ES namespace.](https://github.com/zloirock/core-js/blob/v3.3.4/packages/core-js/modules/es.global-this.js)

**Comment by ryanelian** [comment]
Implemented via https://github.com/ryanelian/ts-polyfill/commit/c901ada10f834044e6dc3c64f97896813f3e8b46
