### ISSUE TITLE
urlSearchParams supported?

### ISSUE THREAD

**Issue by a2life** [ryanelian/ts-polyfill#9]
Hi, I just found this polyfill and quickly tried it in place of 'import core-js' .  The webpack is about 50kb smaller without any fine tuning and the app works but  IE 11 complains it can not find urlSearchParams.  I could of course use 'url-search-params-pollyfill' in addition to 'ts-polyfill' but this seems to be defeating the purpose of this polyfill.  Is there any settings that I needed to tweak?

**Comment by ryanelian** [comment]
Hey there.

>  I could of course use 'url-search-params-pollyfill' in addition to 'ts-polyfill' but this seems to be defeating the purpose of this polyfill. 

I'm gonna correct you on that one. This library purpose is to map each TypeScript libs to core-js polyfills as humanly possible. 

For example, if you add [`es2019.string`](https://github.com/ryanelian/ts-polyfill/blob/master/official-lib-declarations/lib.es2019.string.d.ts) lib then [`import 'ts-polyfill/lib/es2019-string';`](https://github.com/ryanelian/ts-polyfill/blob/master/src/es2019-string.ts) in your project, **you are assured that all API in that lib will be usable.**

Now, that `UrlSearchParams` API is located in the (massive) DOM lib: https://github.com/ryanelian/ts-polyfill/blob/master/official-lib-declarations/lib.dom.d.ts#L16078-L16105

**Being that there's no polyfill for the DOM lib in this library, you are NOT assured that all API in the DOM lib can be used safely. Meaning, it's YOUR responsibility to make sure DOM libs are polyfilled correctly.** 

Fortunately, `UrlSearchParams` polyfill is available on core-js itself: https://github.com/zloirock/core-js#url-and-urlsearchparams so you can add this to your app to polyfill without any extra libraries:

```js
import "core-js/stable/url-search-params";
```

If you would like to map each and every DOM lib to the corresponding polyfill in ts-polyfill, PR welcome.

**Comment by a2life** [comment]
Thanks for the clarification! I am a bit wiser today.
